# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vishal Koosuri
email: vishal.koosuri1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; Developed by Vishal Koosuri
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dainvinc-io-dainvinc.c9users.io/" # the base hostname & protocol for your site
twitter_username: vishal_smarty21
github_username:  dainvinc
linkedin_username: vishal-koosuri-0288a69a

# Build settings
markdown: kramdown